namespace DeejayEntertainment.UnarmedDuallingClub.Sound
{
	public enum Sounds
	{
		Amblush = 0,
		Armageddon = 1,
		Bleed = 2,
		Blind = 3,
		Bloodlast = 4,
		Bubble = 5,
		CharacterSelected = 6,
		Charge = 7,
		CurseHigh = 8,
		CurseLow = 9,
		Cyclone = 10,
		DeathGrip = 11,
		EarthStrike = 12,
		EnergyBolt = 13,
		Enrage = 14,
		Fireball = 15,
		FlameShock = 16,
		Freeze = 17,
		FrostBolt = 18,
		FrostEnrage = 19,
		FrostTrap = 20,
		Heal = 21,
		HighHand = 22,
		HighKick = 23,
		IceShield = 24,
		Jump = 25,
		LowHand = 26,
		LowKick = 27,
		MainMenuChange = 28,
		MainMenuSelect = 29,
		PowerfulKick = 30,
		PowerkickFury = 31,
		Reflect = 32,
		ShadowForm = 33,
		Stealth = 34,
		Stone = 35,
		Storm = 36,
		Stun = 37,
		TankStrike = 38,
		Uppercut = 39,
		Win = 40,
		Lose = 41,
	}
}
