//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeejayEntertainment.UnarmedDuallingClub.GameCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AbilitiesDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AbilitiesDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeejayEntertainment.UnarmedDuallingClub.GameCore.Resources.AbilitiesDescription", typeof(AbilitiesDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способности:.
        /// </summary>
        internal static string AbilitiesTitle {
            get {
                return ResourceManager.GetString("AbilitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Пробивание брони(пассивная). После рывка враг не может использовать блок в течение {0} сек..
        /// </summary>
        internal static string BlockBan {
            get {
                return ResourceManager.GetString("BlockBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Герой получает неуязвимость на {0} сек.
        /// </summary>
        internal static string Bubble {
            get {
                return ResourceManager.GetString("Bubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собирает всю свою ярость и наносит врагу {0} ед. физического урона.
        /// </summary>
        internal static string PowerfulFury {
            get {
                return ResourceManager.GetString("PowerfulFury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) Яростная аура(пассивная). Все лечение, используемое на поле боя с героем уменьшается на 80%..
        /// </summary>
        internal static string RageAura {
            get {
                return ResourceManager.GetString("RageAura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атака, оглушающая противника на {0} сек. и наносящая {1} ед. физического урона.
        /// </summary>
        internal static string StunFury {
            get {
                return ResourceManager.GetString("StunFury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}) {1}. {2}. Перезарядка {3} сек..
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
    }
}
