//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeejayEntertainment.UnarmedDuallingClub.GameCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AbilitiesDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AbilitiesDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeejayEntertainment.UnarmedDuallingClub.GameCore.Resources.AbilitiesDescription", typeof(AbilitiesDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способности:.
        /// </summary>
        internal static string AbilitiesTitle {
            get {
                return ResourceManager.GetString("AbilitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проводит бесконтактную атаку с расстояния. Оглушает на {0} сек. и наносит {1} магического урона раз в {2} сек. Длительность - {3} сек.
        /// </summary>
        internal static string Bleed {
            get {
                return ResourceManager.GetString("Bleed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ослепляет врага на {0} сек.
        /// </summary>
        internal static string Blind {
            get {
                return ResourceManager.GetString("Blind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Пробивание брони(пассивная). После рывка враг не может использовать блок в течение {0} сек..
        /// </summary>
        internal static string BlockBan {
            get {
                return ResourceManager.GetString("BlockBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наполняет свои атаки яростью и наносит на {0}% больше урона. Длительность {1} сек.
        /// </summary>
        internal static string BloodLast {
            get {
                return ResourceManager.GetString("BloodLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Герой получает неуязвимость на {0} сек.
        /// </summary>
        internal static string Bubble {
            get {
                return ResourceManager.GetString("Bubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Силы природы подхватывают противника и делают его неуязвимым на {0} сек. Противник не может ничего сделать, пока действует циклон.
        /// </summary>
        internal static string Cyclone {
            get {
                return ResourceManager.GetString("Cyclone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Притягивает врага к себе.
        /// </summary>
        internal static string DeathGrip {
            get {
                return ResourceManager.GetString("DeathGrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Герой сокрушительно бьет по земле и наносит {0} ед. физического урона, дополнительно оглушая врага на {1} сек. и заставляя молчать на {2} сек.
        /// </summary>
        internal static string EarthStrike {
            get {
                return ResourceManager.GetString("EarthStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускает странный энергетический шар, который наносит противнику {0} ед. магического урона. Если у противника менее 35% здоровья, то он получит в {1} раза больше урона.
        /// </summary>
        internal static string EnergyBolt {
            get {
                return ResourceManager.GetString("EnergyBolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наполняет свои атаки яростью и наносит на {0}% больше урона. Длительность {1} сек.
        /// </summary>
        internal static string Enrage {
            get {
                return ResourceManager.GetString("Enrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замораживает врага на {0} сек.
        /// </summary>
        internal static string Freeze {
            get {
                return ResourceManager.GetString("Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создает ледяную стрелу, наносящую {0} ед. магического урона. Замороженный противник получает в {1} раза больше урона.
        /// </summary>
        internal static string FrostBolt {
            get {
                return ResourceManager.GetString("FrostBolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4)Ледяная ярость(пассивная). Если магу наносят урон, снижающий его здоровье до 25%, то он впадает в ярость и начинает наносить на {0}% больше урона. Длительность {1} сек. Срабатывает только 1 раз за бой..
        /// </summary>
        internal static string FrostEnrage {
            get {
                return ResourceManager.GetString("FrostEnrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исцеляет {0} - {1} ед. здоровья. Перезарядка сбрасывается, если противник в циклоне.
        /// </summary>
        internal static string Heal {
            get {
                return ResourceManager.GetString("Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окружает мага ледяным щитом, который поглощает {0} ед. урона. Если противник пробьет щит, он заморозится на {1} сек. Длительность щита - {2} сек.
        /// </summary>
        internal static string IceShield {
            get {
                return ResourceManager.GetString("IceShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собирает всю свою ярость и наносит врагу {0} ед. физического урона.
        /// </summary>
        internal static string PowerfulFury {
            get {
                return ResourceManager.GetString("PowerfulFury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) Яростная аура(пассивная). Все лечение, используемое на поле боя с героем уменьшается на 80%..
        /// </summary>
        internal static string RageAura {
            get {
                return ResourceManager.GetString("RageAura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Неутомимость(пассивная). Используя рывок, перезарядки всех способностей уменьшаются на {0} сек..
        /// </summary>
        internal static string ReduceCdBurster {
            get {
                return ResourceManager.GetString("ReduceCdBurster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отражает летящий в героя предмет. Длительность - {0} сек.
        /// </summary>
        internal static string Reflection {
            get {
                return ResourceManager.GetString("Reflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Растворяется в тени, наносит на {0}% больше урона, получает на {1}% меньше урона и не может использовать заклинания исцеления.
        /// </summary>
        internal static string ShadowForm {
            get {
                return ResourceManager.GetString("ShadowForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Кара(пассивная). Отражает {0}% любого нанесенного урона. Растворенные в тени противники не получают урона. Растворяет вражеского лекаря в тени..
        /// </summary>
        internal static string Smite {
            get {
                return ResourceManager.GetString("Smite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыться с глаз врага. Действует до отмены.
        /// </summary>
        internal static string Stealth {
            get {
                return ResourceManager.GetString("Stealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создает огромный камень из воздуха и метает его в противника, нанося ему  {0} ед. физического урона и оглушая на {1} сек.
        /// </summary>
        internal static string Stone {
            get {
                return ResourceManager.GetString("Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раскручивается в вихре и начинает наносить удары по {0} ед. физического урона каждые {1} сек. Длительность {2} сек. Существует небольшая вероятность прерывания вихря.
        /// </summary>
        internal static string Storm {
            get {
                return ResourceManager.GetString("Storm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атака, оглушающая противника на {0} сек. и наносящая {1} ед. физического урона.
        /// </summary>
        internal static string StunFury {
            get {
                return ResourceManager.GetString("StunFury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наносит врагу {0} ед. физического урона. Дает провести дальнейшую комбинацию. Пробивает блок.
        /// </summary>
        internal static string TankStrike {
            get {
                return ResourceManager.GetString("TankStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}) {1}. {2}. Перезарядка {3} сек..
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
    }
}
