//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeejayEntertainment.UnarmedDuallingClub.GameCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CharacterDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharacterDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeejayEntertainment.UnarmedDuallingClub.GameCore.Resources.CharacterDescriptions", typeof(CharacterDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы видите перед собой храброго воина, который своим видом вселяет страх в своих врагов. После того, как он приближается к врагу, тот забывает как блокировать атаки. Воин способен собирать всю свою силу и ярость, чтобы нанести сокрушительный удар по врагу, либо оглушить его. В минуту опасности он обращается к силам Света и защищает себя непробиваемым щитом..
        /// </summary>
        internal static string Fury {
            get {
                return ResourceManager.GetString("Fury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек, сеящий вокруг себя добро и свет. Обладает способностью залечивать даже самые тяжелые раны. Призвав на помощь силы природы, может защитить себя от врагов с помощью циклона. Враги опасаются атаковать лекаря, потому что тех, кто его атакует постигает кара. Если лекаря разозлить, он растворится в тени, однако перестанет отражать урон и не сможет лечиться..
        /// </summary>
        internal static string Healer {
            get {
                return ResourceManager.GetString("Healer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот герой обладает несравненной выносливостью. Его кожа прочнее самых тяжелых доспехов, а кулаки тяжелее металла. Говорят, что он может ударить по земле так, что удар дизориентирует Вас и заставит потерять дар речи. Специально подставив себя под магическую атаку, этот воин способен её отразить. Бегите, если он несется в вашу сторону. Удар от столкновения с ним настолько силён, что вас может оглушить..
        /// </summary>
        internal static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
    }
}
