//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeejayEntertainment.UnarmedDuallingClub.GameCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CharacterDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharacterDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeejayEntertainment.UnarmedDuallingClub.GameCore.Resources.CharacterDescriptions", typeof(CharacterDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ловкий и искусный боец ближнего боя, мастерски управляющий своими внутренними ресурсами. Накапливая энергию, способен впадать в ярость и разрушать все, что движется. Обладает исключительным свойством притягивать соперников к себе с помощью верёвки, которую прячет в рукаве. Подождав, пока противник подойдет близко, герой начинает очень быстро крутиться в вихре и наносить молниеносные атаки..
        /// </summary>
        internal static string Burster {
            get {
                return ResourceManager.GetString("Burster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мастер комбинаций из ударов владеет несравненной скоростью ударов. Его враги не успевают уклониться от одного удара, как тут же получают следующий. Ходят слухи, что как-то раз победив одного мага, он заставил его поделиться своими секретами, после чего научился создавать из воздуха тяжелейшие камни и странные энергетические шары, которые высасывают жизненную энергию у тяжело раненных врагов..
        /// </summary>
        internal static string Combinator {
            get {
                return ResourceManager.GetString("Combinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Представляем Вам повелителя огня и молний. Искусно балансируя между силами огня и электричества он может повергнуть любого противника. Атакуя цель огнем, он дает ей привыкнуть к своим огненным атакам, а затем резко меняет тактику, призывая с неба молнии, которые, застав врага врасплох, наносят колоссальный урон не сопоставимый с жизнью. Силы огня также помогают магу защищаться от атак, создавая щиты и оглушая врагов..
        /// </summary>
        internal static string FireMage {
            get {
                return ResourceManager.GetString("FireMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перед Вами один из лучших магов льда. Лед - его жизнь. Его прошлое, настоящее и будущее. Никто не знает, как растопить его ледяную сущность. Он замораживает всех своих врагов и разбивает их вдребезги. Он умеет сосредоточить в себе весь дух льда и создать мощный ледяной барьер, который защищает его от всех атак и замораживает тех, кто посмеет его разбить. Если у мага останется мало здоровья, он впадет в древнюю ледяную ярость и изничтожает всех врагов на своем пути..
        /// </summary>
        internal static string FrostMage {
            get {
                return ResourceManager.GetString("FrostMage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы видите перед собой храброго воина, который своим видом вселяет страх в своих врагов. После того, как он приближается ко врагу, тот забывает как блокировать атаки. Воин способен собирать всю свою силу и ярость, чтобы наносить сокрушительные удары по врагу, оглушая его. В минуту опасности он обращается к силам света и защищает себя непробиваемым щитом..
        /// </summary>
        internal static string Fury {
            get {
                return ResourceManager.GetString("Fury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Герой, сеящий вокруг себя добро и свет. Обладает способностью залечивать самые тяжелые раны. Призвав на помощь силы природы, может защитить себя от врагов с помощью циклона. Они опасаются атаковать лекаря, потому что тех, кто его атакует постигает кара. Если лекаря разозлить, он растворится в тени, станет особо опасен, но не сможет лечиться..
        /// </summary>
        internal static string Healer {
            get {
                return ResourceManager.GetString("Healer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прирожденный ловчайший наёмный убийца, который знает все болевые точки своих врагов. Его руки, словно клинки, вонзаются во врагов и быстро их убивают. Он умеет скрываться с глаз врага, телепортироваться к нему за спину и наносить сокрушительные удары. Умение ослеплять врага позволяет ему безнаказанно делать с ним все, что он захочет. Ходят слухи, что невидимый герой владеет техникой бесконтактного боя и может заставить врага кровоточить с расстояния..
        /// </summary>
        internal static string Stealther {
            get {
                return ResourceManager.GetString("Stealther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Герой обладающий несравненной выносливостью. Его кожа прочнее самых тяжелых доспехов, а кулаки тяжелее металла. Говорят, что он может ударить по земле так, что удар дизориентирует Вас и заставит потерять дар речи. Специально подставив себя под магическую атаку, этот воин способен её отразить. Бегите, если он несется в вашу сторону. Удар от столкновения с ним настолько силён, что может вас оглушить..
        /// </summary>
        internal static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темными силами повелевает чернокнижник. Он способен высасывать жизненную силу врага и восстанавливать за его счет свою. Темные силы чернокнижника неограничены. Он будет проклинать врага до тех пор, пока тот не испустит дух. Темный маг также может использовать свои силы, чтобы заморозить тьмой или ослепить. Время - главный союзник чернокнижника,так как заклинания, наложенные им, действуют практически вечно..
        /// </summary>
        internal static string Warlock {
            get {
                return ResourceManager.GetString("Warlock", resourceCulture);
            }
        }
    }
}
