//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeejayEntertainment.UnarmedDuallingClub.GameCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatsDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatsDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeejayEntertainment.UnarmedDuallingClub.GameCore.Resources.StatsDescriptions", typeof(StatsDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ловкость.
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Духанов Данила.
        /// </summary>
        internal static string Dan {
            get {
                return ResourceManager.GetString("Dan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Милёхин Дмитрий.
        /// </summary>
        internal static string Dmitry {
            get {
                return ResourceManager.GetString("Dmitry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интеллект.
        /// </summary>
        internal static string Intellegence {
            get {
                return ResourceManager.GetString("Intellegence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апсаликов Михаил.
        /// </summary>
        internal static string Mikhail {
            get {
                return ResourceManager.GetString("Mikhail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иванов Сергей.
        /// </summary>
        internal static string Sergey {
            get {
                return ResourceManager.GetString("Sergey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выносливость.
        /// </summary>
        internal static string Stamina {
            get {
                return ResourceManager.GetString("Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель персонажа - {0}.
        ///Основная характеристка - {1}.
        ///Максимальное здоровье - {2}.
        ///Броня - {3}.
        ///Вероятность критического удара - {4}%..
        /// </summary>
        internal static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
    }
}
